package com.stackroute.playerservice.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Player data class
 * Getter,setter,parameterised constructor, default constructor generated by lombok
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Player {

    /**
     * auto generated id as primary key
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id ;
    private String name ;
    private int score ;


}
